# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
env:
  - PKG_TARBALL=rayshaderanmiate_1.0.0.tar.gz
sudo: required

cache:
 - packages
 - apt: true
pandoc_version: 1.19.2.1
r_github_packages:
  - r-lib/pkgdown
  - tylermorganwall/rayshader

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libxml2-dev
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - libxxf86vm-dev
      - x11proto-xf86vidmode-dev
      - xvfb
      - cargo
      - libgs-dev
      - qpdf
      - ghostscript

matrix:
  include:
  - r: release
    script:
      - R CMD build . --compact-vignettes=gs+qpdf
      - xvfb-run R CMD check *tar.gz
    after_success:
      - tar -C .. -xf $PKG_TARBALL
      - rm -rf RTest.Rcheck
      - Rscript -e 'pkgdown::build_site()'
    deploy:
      - provider: releases
        api_key: $GITHUB_TOKEN
        file: $PKG_TARBALL
        skip_cleanup: true
        on:
          tags: true
      - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: docs
        on:
          branch: master
